<a href="https://colab.research.google.com/github/Karthik-varma-I/Pytorch_basics/blob/main/pytorch_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aggregation functions

In [ ]:
import torch

In [ ]:
ten1=torch.tensor([1, 2,3,4,5,6,7])

In [ ]:
#min
print(ten1.min())
print(torch.min(ten1))

tensor(1)
tensor(1)


In [ ]:
#max
print(ten1.max())
print(torch.max(ten1))

tensor(7)
tensor(7)


In [ ]:
#mean
print(ten1.type(torch.float32).mean())
print(torch.mean(ten1.type(torch.float32)))

tensor(4.)
tensor(4.)


In [ ]:
#sum
print(ten1.sum())
print(torch.sum(ten1))

tensor(28)
tensor(28)


#position of min and max

In [ ]:
#min
ten1.argmin()

tensor(0)

In [ ]:
#max
ten1.argmax()

tensor(6)

#Reshaping, squeezing, unsqueezing and stacking tensors

* reshaping-reshapes the tensor into defined shape.
* view-return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* stacking-combines multiple tensors on the top of each other(vstack) or side by side(hstack).
* squeeze-removes all 1 dimensions from tensor.
* unsqueeze-add 1 dimension to a targed tensor.
* permute-return a view of inputwith dimensions permuted(swapped) in a certain way.

In [1]:
import torch
ten1=torch.arange(1.,10.)
ten1,ten1.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [4]:
#reshape
ten2=ten1.reshape(3,3)
ten2

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [13]:
#change the view
a=ten2.view(3,3)
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [19]:
a[:,0]=123
a,ten2,ten1

(tensor([[123.,   2.,   3.],
         [123.,   5.,   6.],
         [123.,   8.,   9.]]),
 tensor([[123.,   2.,   3.],
         [123.,   5.,   6.],
         [123.,   8.,   9.]]),
 tensor([123.,   2.,   3., 123.,   5.,   6., 123.,   8.,   9.]))

In [18]:
b=torch.stack([ten1,ten1,ten1],dim=0)#hstack
c=torch.stack([ten1,ten1],dim=1)#vstack
b,c

(tensor([[123.,   2.,   3., 123.,   5.,   6., 123.,   8.,   9.],
         [123.,   2.,   3., 123.,   5.,   6., 123.,   8.,   9.],
         [123.,   2.,   3., 123.,   5.,   6., 123.,   8.,   9.]]),
 tensor([[123., 123.],
         [  2.,   2.],
         [  3.,   3.],
         [123., 123.],
         [  5.,   5.],
         [  6.,   6.],
         [123., 123.],
         [  8.,   8.],
         [  9.,   9.]]))

In [21]:
ten3=torch.tensor([[1,2,3]])
ten3,ten3.shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [23]:
#squeeze
ten4=ten3.squeeze()
print(ten3,ten3.shape)
print("\n")
ten4,ten4.shape

tensor([[1, 2, 3]]) torch.Size([1, 3])




(tensor([1, 2, 3]), torch.Size([3]))

In [28]:
#unsqueeze
ten5=ten3.unsqueeze(dim=0)#dim=0
ten6=ten4.unsqueeze(dim=1)#dim=1
ten7=ten6.unsqueeze(dim=1)#dim=1
print(ten3,ten3.shape)
print("\n")
print(ten5,ten5.shape)
print(ten6,ten6.shape)
ten7,ten7.shape

tensor([[1, 2, 3]]) torch.Size([1, 3])


tensor([[[1, 2, 3]]]) torch.Size([1, 1, 3])
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])


(tensor([[[1]],
 
         [[2]],
 
         [[3]]]),
 torch.Size([3, 1, 1]))

In [30]:
ten8=torch.rand(2,3,4)
print(ten8,ten8.shape)
ten9=ten8.permute(2,0,1)
ten9,ten9.shape

tensor([[[0.0409, 0.2987, 0.0317, 0.9924],
         [0.7153, 0.4281, 0.2127, 0.8718],
         [0.2656, 0.0339, 0.5178, 0.4048]],

        [[0.8605, 0.9177, 0.5609, 0.2436],
         [0.1290, 0.4902, 0.6997, 0.5756],
         [0.6149, 0.4403, 0.9692, 0.2573]]]) torch.Size([2, 3, 4])


(tensor([[[0.0409, 0.7153, 0.2656],
          [0.8605, 0.1290, 0.6149]],
 
         [[0.2987, 0.4281, 0.0339],
          [0.9177, 0.4902, 0.4403]],
 
         [[0.0317, 0.2127, 0.5178],
          [0.5609, 0.6997, 0.9692]],
 
         [[0.9924, 0.8718, 0.4048],
          [0.2436, 0.5756, 0.2573]]]),
 torch.Size([4, 2, 3]))

#pytorch and numpy
* numpy-> pytorch tensor = torch.from_numpy(nparray)
*pytorch tensor -> numpy =torch.Tensor.numpy().

In [37]:
import numpy as np
arr=np.arange(1.,10.)
ten1=torch.from_numpy(arr)
print(ten1)
arr+=1
print(arr,ten1)
arr=arr+1
print(arr,ten1)
arr[0]=10
print(arr,ten1)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.] tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
[ 3.  4.  5.  6.  7.  8.  9. 10. 11.] tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
[10.  4.  5.  6.  7.  8.  9. 10. 11.] tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)


In [39]:
ten2=torch.arange(9.)
arr=ten2.numpy()
ten2,arr

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32))

#Reproducibility

In [40]:
torch.manual_seed(111)
ten1=torch.rand(1,4)
ten2=torch.rand(1,4)
print(ten1,ten2)
print(ten1==ten2)
torch.manual_seed(111)
ten3=torch.rand(1,4)
print(ten3)
print(ten1==ten3)

tensor([[0.7156, 0.9140, 0.2819, 0.2581]]) tensor([[0.6311, 0.6001, 0.9312, 0.2153]])
tensor([[False, False, False, False]])
tensor([[0.7156, 0.9140, 0.2819, 0.2581]])
tensor([[True, True, True, True]])


In [41]:
torch.manual_seed(111)
ten4=torch.rand(1,5)
ten4

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311]])