<a href="https://colab.research.google.com/github/Karthik-varma-I/Pytorch_basics/blob/main/pytorch_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


#Introduction to tensors

In [7]:
# Tensors are created Using torch.tensor()
zeroD=torch.tensor(10)
zeroD

tensor(10)

In [8]:
print(zeroD.ndim) #0D
print(zeroD.shape)

0
torch.Size([])


In [9]:
zeroD.item()

10

In [10]:
oneD=torch.tensor([1,2,3]) #1D
oneD

tensor([1, 2, 3])

In [11]:
oneD.ndim

1

In [12]:
oneD.shape

torch.Size([3])

In [13]:
twoD=torch.tensor([[1,2,3],[4,5,6]]) #2D
twoD

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
print(twoD.ndim)
print(twoD.shape)

2
torch.Size([2, 3])


In [15]:
print(twoD[1])
print(twoD[1,2])

tensor([4, 5, 6])
tensor(6)


In [16]:
tensor1=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]]) #multi dimensional
tensor1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [11, 12, 13]]])

In [17]:
print(tensor1.ndim)
print(tensor1.shape)

3
torch.Size([2, 2, 3])


In [18]:
print(tensor1[1,1,0]) #11

tensor(11)


#Random Tensors

In [19]:
rand_tensor=torch.rand(2,2,2)
rand_tensor

tensor([[[0.6165, 0.5547],
         [0.7162, 0.8747]],

        [[0.2810, 0.8629],
         [0.3641, 0.3583]]])

Zeros and Ones

In [20]:
zero_tensor=torch.zeros(size=(2,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
one_tensor=torch.ones(2,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

#Creating a range of tensors and tensors-like

In [22]:
tensor_range=torch.arange(1,6)
tensor_range

tensor([1, 2, 3, 4, 5])

In [23]:
zero_tensor1=torch.zeros_like(tensor_range)
zero_tensor1

tensor([0, 0, 0, 0, 0])

#Tensor Datatypes

In [24]:
d_type=torch.tensor([1,2,3],
             dtype=None, #data type of tensor.
             device=None, #what device is your tensor on.
             requires_grad=False #whether or not to track with this tensor operations
             )
d_type

tensor([1, 2, 3])

In [25]:
ten1=torch.tensor([1,2,3],dtype=torch.float16)
ten1

tensor([1., 2., 3.], dtype=torch.float16)

In [26]:
ten2=torch.tensor([1,2,3],dtype=torch.int32)
ten2

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
ten2=torch.rand([2,3])
print(ten2)

tensor([[0.5214, 0.4569, 0.2394],
        [0.0962, 0.6213, 0.5228]])


#Tensor Attributes

In [28]:
print(ten2.dtype)
print(ten2.device)
print(ten2.shape)

torch.float32
cpu
torch.Size([2, 3])


#Manipulating tensors

In [29]:
ten3=torch.tensor([1,2,3,4,5])
ten3

tensor([1, 2, 3, 4, 5])

In [35]:
#Addition
print(ten3+10)
#using built-in fun
print(torch.add(ten3,10))
#substraction
print(ten3-10)
print(torch.sub(ten3,10))
#multiplication
print(ten3*10)
print(torch.mul(ten3,10))
#division
print(ten3/10)
print(torch.div(ten3,10))

tensor([11, 12, 13, 14, 15])
tensor([11, 12, 13, 14, 15])
tensor([-9, -8, -7, -6, -5])
tensor([-9, -8, -7, -6, -5])
tensor([10, 20, 30, 40, 50])
tensor([10, 20, 30, 40, 50])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])


#Matrix Multiplication

In [37]:
print(torch.matmul(ten3,ten3)) #dot product

tensor(55)


In [40]:
torch.matmul(torch.rand(2,3),torch.rand(3,3))

tensor([[1.4038, 0.5967, 1.4563],
        [1.1002, 0.5969, 1.4215]])

In [41]:
#Transpose
ten1=torch.tensor([[1,2,3],[3,4,5]])
print(ten1)
print("Transpose :")
print(ten1.T)

tensor([[1, 2, 3],
        [3, 4, 5]])
Transpose :
tensor([[1, 3],
        [2, 4],
        [3, 5]])


In [42]:
print(torch.matmul(ten1,ten1.T))

tensor([[14, 26],
        [26, 50]])


In [43]:
print(ten1.T.shape)

torch.Size([3, 2])
